### ISSUE TITLE
Issues with preview on: Dev environment "Missing form token from Request" and timeout on prod on first load

### ISSUE THREAD

**Issue by damaya** [netgen/NetgenAdminUIBundle#10]
- eZ Version: **5.4.11** 
Description: When click on preview button, on Development environment, i get error "Missing form token from Request..."
<img width="1264" alt="captura de pantalla 2018-01-09 a la s 8 27 10 p m" src="https://user-images.githubusercontent.com/600611/34751583-874b91be-f57b-11e7-9c2a-0d530a5fb845.png">
On production site, instead, i get a timeout error at first time, but then the preview loads correctly, but in the logs i get:

`PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 32 bytes) in /home/ubuntu/mysite/adminui/vendor/tedivm/stash/src/Stash/Pool.php on line 133, referer: https://adminui.mysite/ngadminui/Created-Folder-test
[Tue Jan 09 19:43:12.410049 2018] [:error] [pid 2071] [client 127.0.0.1:40643] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 64 bytes) in /home/ubuntu/mysite/adminui/vendor/symfony/symfony/src/Symfony/Component/Debug/Exception/FlattenException.php on line 270`

In another case , i installed the adminui in a clean ez **5.4.10** site, but could not replicate the same issue, i'll keep searching if there is any configuration error from my side, but any help would be appreciated.

Thanks in advance.

**Comment by emodric** [comment]
Hi @damaya,

We will try to upgrade one of our sites to 5.4.11 from 5.4.10 in coming days and see if we can reproduce the issue. Until then, there's not much I can help with, since this is the first time I'm seeing this.

Thanks for reporting it and let me know if you find out anything :)

**Comment by damaya** [comment]
Hi @emodric thanks for your answer, sure, in any case i'll give you my feedback about this.

Kind regards.

**Comment by damaya** [comment]
Hi @emodric additional, i forgot to comment that we are using symfony 2.8 with ez 5.4.11

**Comment by damaya** [comment]
Hi @emodric i see this works fine whith 5.4.10 and 5.4.11 but when the *ezformtoken* is disabled, when enabled, i get the token error.

**Comment by emodric** [comment]
@damaya Okay! We'll look into it, thanks!

**Comment by emodric** [comment]
@damaya I've managed to reproduce the issue and fixed it in https://github.com/netgen/NetgenAdminUIBundle/commit/691f58c4c730c0cbc1721b802363514d71554e9c

Can you test the `2.1-release` branch to verify the fix and I will tag the 2.1.4 version then?

Thanks!

**Comment by damaya** [comment]
Hi there @emodric thanks a lot for your update, sure i'll test this today 👍 :)

**Comment by damaya** [comment]
Hi @emodric i tested and it works like a charm! 👍  thank you very much, you rules!

**Comment by emodric** [comment]
@damaya Thank you for testing :)

I've released version 2.1.4 with the fix: https://github.com/netgen/NetgenAdminUIBundle/releases/tag/2.1.4
