### ISSUE TITLE
Use legacy search engine

### ISSUE THREAD

**Issue by damaya** [netgen/NetgenAdminUIBundle#12]
Hi there, may be this is not an issue, but would you like to give me a hand in finding a way to use the legacy search from the adminui? i tried this, https://doc.ez.no/display/EZP/Legacy+Search+Engine+Bundle but didn't work, ¿should i use this https://doc.ez.no/display/EZP/Solr+Search+Engine+Bundle?
Thanks in advance

**Comment by emodric** [comment]
Hi!

How about using [ezplatformsearch](https://github.com/netgen/ezplatformsearch) legacy extension? It allows you to use any search engine configured in eZ Platform, directly in Netgen Admin UI.

**Comment by damaya** [comment]
Hi, thanks for your answer, sure! i'll test this :)
