### ISSUE TITLE
ReferenceError: params is not defined

### ISSUE THREAD

**Issue by SalvatorePollaci** [netgen/NetgenAdminUIBundle#16]
Hi,
I'm trying to install 'Netgen Admin UI' via legacy bridge on top of a eZ Platform v2 Communty Edition installed via eZ Launchpad(https://www.netgenlabs.com/Blog/How-to-start-using-Netgen-Admin-UI). I am correctly seeing eZ Platform v2 Admin(content etc) and I am correctly seeing most of Netgen Admin UI panels but when I visit 'Content Structure' or 'User Accounts' panels the page is empty.

I see the following errors in developer console:
```
ReferenceError: params is not defined
```

I have discovered the file responsible for this error is the following:
```
/ezpublish_legacy/extension/ngadminui/design/ngadminui/templates/contentstructuremenu/content_structure_menu_dynamic.tpl
```

It seems that variable 'params' gets initialized in a 'cache-block' which is not being executed.

Do you have any idea how to resolve this issue?

Thanks

**Comment by SalvatorePollaci** [comment]
After debugging code, it seems to be a cache problem.
If I comment out the {cache-block and {/cache-block} lines, the 'params is not defined' error disappears as the params variable gets initialized inside these cache blocks.

```
var params = {ldelim}{*
            *}"iconsList":[],{*
            *}"contentTreeUrl":"{"content/treemenu"|ezurl(no)}/",{*
            *}"wwwDirPrefix":"{ezsys('wwwdir')}/{$iconInfo.theme_path}/{$iconInfo.size_path_list[$classIconsSize]}/"{rdelim};
```

Consequently the dynamic content tree menu returns string 'Internal Error' as the following API returns 0 bytes:
```
http://localhost:42080/ngadminui/content/treemenu/2/1301073466/1532623035/43b864bde60564a9abad0598b1d5d203
```

To get the API to return content I must set 'UseCache' to 'disabled' in:
```
/ezpublish_legacy/settings/siteaccess/ngadminui/contentstructuremenu.ini.append.php
```

Now I can correctly see dynamic content tree menu, but when I click on a node, no content is shown. It seems that this content should come from:
```
/vendor/netgen/admin-ui-bundle/bundle/Resources/views/pagelayout_module.html.twig
{% block content %}
    {{ module_result.content|raw }}
{% endblock %}
```

but module_result.content is an empty string.

Do you have any idea how to risolve this issue?

Ps I can correctly see edit interface for such content, so communication with DB is fine.

**Comment by SalvatorePollaci** [comment]
After a long debug session I found that the problem is due to Legacy Bridge forcing 'site.ini/ContentSettings/ViewCaching' to 'enabled' in file:

/vendor/ezsystems/legacy-bridge/bundle/LegacyMapper/Configuration.php
```
// Cache settings
// Enforce ViewCaching to be enabled in order to persistence/http cache to be purged correctly.
$settings['site.ini/ContentSettings/ViewCaching'] = 'enabled';
```

It's not possible to override such setting in site.ini.append.php as ezini.php line 1428 gives priority to injected settings.

Do you know how I can disable ViewCaching or leave it enabled but having panels working correctly?

**Comment by emodric** [comment]
Hi @SalvatorePollaci !

I must say I've never ran into this issue before. As you debugged yourself, you can't really disable view caching, because then clearing of persistence cache would not work.

Do you maybe have some unusual configuration that might cause these issues?

**Comment by SalvatorePollaci** [comment]
Hi @emodric,
as far as I know, I don't have any unusual configurations. I simply installed eZ via eZ launchpad with standard config, then I followed the Netgen Admin Ui installation guide here https://www.netgenlabs.com/Blog/How-to-start-using-Netgen-Admin-UI.

I'm now looking into the path where cache files are stored. Maybe that might help me understand what is happening.

**Comment by emodric** [comment]
You think that eZ Launchpad might be an issue?

**Comment by SalvatorePollaci** [comment]
Hi @emodric,
according to method handle in class eZTemplateCacheBlock
/ezpublish_legacy/lib/eztemplate/classes/eztemplatecacheblock.php

eZ is looking for cache block files such as:
var/site/cache/template-block/3/f/1/3f1f39691ec146e535610c4eaa79d0d0.cache

where 'site' is the siteaccess.

The problem here is that in /ezpublish_legacy/var/site/cache there is no folder 'template-block'.

Do you know how to risolve this issue?

**Comment by SalvatorePollaci** [comment]
Hi @emodric,
sorry for number of messages. To sum up I have 2 problems:
1)Dynamic content tree menu is not loading
2)Content Panel is not loading

**Solution to Problem 1**
I have just found the solution to problem 1.
Even though, according to the 'Ini settings' panel, '[TemplateSettings]/TemplateCache' has value 'enabled' for siteaccess 'ngadminui', I had to set such value in 
/ezpublish_legacy/settings/siteaccess/ngadminui/site.ini.append.php

**Solution to Problem 2**
I have only found a workaround to such problem. I have to override
```

**Comment by emodric** [comment]
I never ran into the issue of panels being empty when view caching is enabled, so I presume it is not the real cause of the issue.

Have you tried installing Netgen Admin UI on a clean install of eZ Platform with Legacy Bridge? For example, by using https://github.com/emodric/ezplatform-legacy ?

**Comment by SalvatorePollaci** [comment]
I've finally found out the real reason why Legacy Panels are empty: https://github.com/ezsystems/launchpad/issues/56

This issue can now be closed.

Thanks
