### ISSUE TITLE
Change password does not properly clear the cache

### ISSUE THREAD

**Issue by peterkeung** [netgen/NetgenAdminUIBundle#30]
If you use "Change Information", which edits the user object and then change the user's password, this works.

However, if you use "Change password" (which goes to /user/password) and then change the password, it does not work until you clear the cache, such as deleting the view cache for that user object.

**Comment by peterkeung** [comment]
Looks like this is because the Netgen Admin UI uses /logout. If the user logs out with /user/logout then the problem is solved. Thus, not sure whether the solution is better in /logout or in the legacy code. In the legacy code, we can address it like this:

`diff --git a/ezpublish_legacy/kernel/user/ezuseroperationcollection.php b/ezpubl
ish_legacy/kernel/user/ezuseroperationcollection.php
index c3f5d6190..13eba1223 100644
--- a/ezpublish_legacy/kernel/user/ezuseroperationcollection.php
+++ b/ezpublish_legacy/kernel/user/ezuseroperationcollection.php
@@ -321,6 +321,8 @@ class eZUserOperationCollection
// "Draft" must be in sync with the PersistentObject
self::updateUserDraft( $user );

+ eZContentCacheManager::clearContentCacheIfNeeded( $userID );
+
return array( 'status' => true );
}
else`

@emodric Any thought on this before I submit a PR to the eZ legacy repo?

**Comment by emodric** [comment]
Admin uses `/logout` because it runs in `legacy_mode: false` context. I don't think we can go around that and start using `/user/logout`.

That being said, it probably should be fixed on both legacy and Netgen Admin UI side.

**Comment by peterkeung** [comment]
I've created a PR now: https://github.com/ezsystems/ezpublish-legacy/pull/1426

**Comment by peterkeung** [comment]
For some added colour: this is not caused by the Netgen Admin UI. It's just more obvious to see the issue with the Netgen Admin UI since you would try to log in to a siteaccess with legacy_mode:false. This issue can be reproduced by 1) changing your password with /user/password; 2) logging in to any siteaccess with legacy_mode:false.

**Comment by emodric** [comment]
@peterkeung Can this one be closed now that https://github.com/ezsystems/ezpublish-legacy/pull/1426 is merged?

**Comment by peterkeung** [comment]
Yes :)
